### ISSUE TITLE
Question: Ignore Attributes

### ISSUE THREAD

**Issue by JustBarnt** [pamoller/xmlformatter#15]
Is there a way to make the formatter not re-order attributes? I've tried the `--preserve` flag but I can't seem to find any way to prevent it from re-ordering my attributes

**Comment by hartwork** [comment]
Line…
https://github.com/pamoller/xmlformatter/blob/ebbc3b307c93ba44629686703ba6908fe2e0c558/xmlformatter.py#L725
…seems to be related. If that's the right spot, the behavior is currently unconditional.

**Comment by pamoller** [comment]
closed with v0.2.7
